name: fruits_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # A better SDK range

dependencies:
  bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.0
  shared_preferences: ^2.5.3
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

# The invalid 'flutter_assets:' section has been REMOVED.
assets_config:
  assets_path: assets/images/
  output_class_name: Assets
  output_file_path: lib/core/utils/app_images.dart
